FROM ubuntu
RUN apt-get update
RUN apt-get install maven openjdk-8-jdk -y
WORKDIR /app
COPY pom.xml .
RUN mvn verify
COPY . .
RUN mvn verify
FROM alpine
RUN apk add openjdk8-jre-base
WORKDIR target
COPY --from=0 /app/target .
CMD ["java", "-Xmx8m", "-Xms8m", "-jar", "words.jar"]